import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../../core/contracts/contract_service.dart';
import '../../../core/contracts/models/contract_model.dart';
import '../../../core/theme/app_colors.dart';

class AddContractScreen extends StatefulWidget {
  const AddContractScreen({super.key});

  @override
  State<AddContractScreen> createState() => _AddContractScreenState();
}

class _AddContractScreenState extends State<AddContractScreen> {
  bool _isLoading = false;

  final _titleController = TextEditingController();
  final _contractNumController = TextEditingController();
  final _vendorController = TextEditingController();
  final _valueController = TextEditingController();

  DateTime? _startDate;
  DateTime? _endDate;
  String _selectedCurrency = 'LE';

  final _currencyOptions = ['LE', 'USD', 'EUR', 'GBP'];

  @override
  void dispose() {
    _titleController.dispose();
    _contractNumController.dispose();
    _vendorController.dispose();
    _valueController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    final title = _titleController.text.trim();
    if (title.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Contract title is required.')),
      );
      return;
    }

    if (_startDate == null || _endDate == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Start and end dates are required.')),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      final valueStr = _valueController.text.trim();
      final newContract = ContractModel(
        id: '', // Generated by ContractService
        companyId: '', // Handled by ContractService
        title: title,
        contractNumber: _contractNumController.text.trim(),
        vendor: _vendorController.text.trim(),
        value: valueStr.isEmpty ? '0' : valueStr,
        currency: _selectedCurrency,
        startDateMs:
            _startDate?.millisecondsSinceEpoch ??
            DateTime.now().millisecondsSinceEpoch,
        endDateMs:
            _endDate?.millisecondsSinceEpoch ??
            DateTime.now().millisecondsSinceEpoch,
        status: _calculateStatus(_endDate ?? DateTime.now()),
        createdAtMs: DateTime.now().millisecondsSinceEpoch,
      );

      final contractService = context.read<ContractService>();
      final success = await contractService.addContract(newContract);

      if (!mounted) return;

      if (success) {
        Navigator.of(context).pop(true);
      } else {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              contractService.lastError ?? 'Failed to add contract',
            ),
            backgroundColor: Colors.red.shade700,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error: ${e.toString()}'),
            backgroundColor: Colors.red.shade700,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  String _calculateStatus(DateTime endDate) {
    if (endDate.isBefore(DateTime.now())) {
      return 'Expired';
    }
    return 'Active';
  }

  Future<void> _pickDate(
    BuildContext context, {
    required DateTime? initialDate,
    required ValueChanged<DateTime?> onSelected,
  }) async {
    final now = DateTime.now();
    final result = await showDatePicker(
      context: context,
      initialDate: initialDate ?? now,
      firstDate: DateTime(now.year - 15),
      lastDate: DateTime(now.year + 15),
    );
    if (result != null) onSelected(result);
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: AppColors.background,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(
            Icons.arrow_back_ios_new_rounded,
            color: AppColors.primary,
          ),
          onPressed: () => Navigator.of(context).maybePop(),
        ),
        title: Text(
          'Add Contract',
          style: theme.textTheme.titleLarge?.copyWith(
            color: AppColors.textPrimary,
            fontWeight: FontWeight.w600,
          ),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Container(
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(20),
            border: Border.all(color: AppColors.border),
          ),
          padding: const EdgeInsets.all(20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              _buildTextField(_titleController, 'Contract Title'),
              const SizedBox(height: 16),
              _buildTextField(_contractNumController, 'Contract Number'),
              const SizedBox(height: 16),
              _buildTextField(_vendorController, 'Vendor/Party Name'),
              const SizedBox(height: 16),
              Row(
                children: [
                  Expanded(
                    flex: 2,
                    child: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 12),
                      decoration: BoxDecoration(
                        color: AppColors.surfaceVariant,
                        borderRadius: BorderRadius.circular(12),
                      ),
                      child: DropdownButtonHideUnderline(
                        child: DropdownButton<String>(
                          value: _selectedCurrency,
                          isExpanded: true,
                          items: _currencyOptions.map((c) {
                            return DropdownMenuItem(value: c, child: Text(c));
                          }).toList(),
                          onChanged: (v) {
                            if (v != null) {
                              setState(() => _selectedCurrency = v);
                            }
                          },
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    flex: 5,
                    child: _buildTextField(
                      _valueController,
                      'Contract Value',
                      keyboardType: TextInputType.number,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),
              Row(
                children: [
                  Expanded(
                    child: _buildDateField(
                      'Start Date',
                      _startDate,
                      () => _pickDate(
                        context,
                        initialDate: _startDate,
                        onSelected: (v) => setState(() => _startDate = v),
                      ),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: _buildDateField(
                      'End Date',
                      _endDate,
                      () => _pickDate(
                        context,
                        initialDate: _endDate ?? _startDate,
                        onSelected: (v) => setState(() => _endDate = v),
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 32),
              _isLoading
                  ? const SizedBox.shrink()
                  : ElevatedButton(
                      style: ElevatedButton.styleFrom(
                        backgroundColor: AppColors.primary,
                        foregroundColor: Colors.white,
                        padding: const EdgeInsets.symmetric(vertical: 16),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12),
                        ),
                      ),
                      onPressed: _submit,
                      child: const Text(
                        'Save Contract',
                        style: TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                    ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildTextField(
    TextEditingController controller,
    String hint, {
    TextInputType? keyboardType,
  }) {
    return TextField(
      controller: controller,
      keyboardType: keyboardType,
      decoration: InputDecoration(
        hintText: hint,
        filled: true,
        fillColor: AppColors.surfaceVariant,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
        contentPadding: const EdgeInsets.symmetric(
          horizontal: 16,
          vertical: 16,
        ),
      ),
    );
  }

  Widget _buildDateField(String hint, DateTime? date, VoidCallback onTap) {
    final hasDate = date != null;
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(12),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
        decoration: BoxDecoration(
          color: AppColors.surfaceVariant,
          borderRadius: BorderRadius.circular(12),
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Text(
              hasDate ? date.toString().split(' ')[0] : hint,
              style: TextStyle(
                color: hasDate
                    ? AppColors.textPrimary
                    : AppColors.textSecondary,
              ),
            ),
            const Icon(
              Icons.calendar_today_rounded,
              size: 18,
              color: AppColors.textSecondary,
            ),
          ],
        ),
      ),
    );
  }
}
